#!/usr/bin/env bash
# Script: group_apache_logs.sh
# Description: Groups visitors by IP and HTTP status code and displays the data.

awk '{count[$1" "$9]++} END {for (key in count) print count[key], key}' apache-access.log | sort -nr
